import React, { useState, useEffect } from 'react';
import { Search, Download, Copy, Check, Building2, Mail, Globe } from 'lucide-react';

const rawData = [
  { name: "Careem", type: "Tech / Super App", email: "careers@careem.com" },
  { name: "Dubizzle", type: "Online Marketplace", email: "careers@dubizzle.com" },
  { name: "Talabat", type: "Food Tech", email: "careers@talabat.com" },
  { name: "Noon", type: "E-commerce", email: "careers@noon.com" },
  { name: "G42 (Group 42)", type: "AI / Cloud Computing", email: "careers@g42.ai" },
  { name: "Kitopi", type: "Cloud Kitchen / Tech", email: "careers@kitopi.com" },
  { name: "Bayzat", type: "HR Tech / SaaS", email: "careers@bayzat.com" },
  { name: "Tabby", type: "Fintech", email: "careers@tabby.ai" },
  { name: "Amazon UAE (Souq)", type: "E-commerce", email: "careers@amazon.ae" },
  { name: "Etisalat Digital", type: "Telecom / IoT / Cloud", email: "careers@etisalat.ae" },
  { name: "du (EITC)", type: "Telecom / ICT", email: "recruitment@du.ae" },
  { name: "Alef Education", type: "EdTech", email: "careers@alefeducation.com" },
  { name: "Property Finder", type: "PropTech", email: "careers@propertyfinder.ae" },
  { name: "Fetchr", type: "Logistics Tech", email: "careers@fetchr.us" },
  { name: "Telegram", type: "Tech / Messaging", email: "Not Available" },
  { name: "10Pearls", type: "Software Development", email: "jobs@10pearls.com" },
  { name: "3i Infotech", type: "IT Services", email: "careers@3i-infotech.com" },
  { name: "Intertec Systems", type: "Systems Integration", email: "careers@intertecsystems.com" },
  { name: "Alpha Data", type: "IT Infrastructure", email: "careers@alpha.ae" },
  { name: "MDS Computers", type: "IT Services", email: "hr@mds.ae" },
  { name: "Emitac Enterprise Solutions", type: "IT Solutions", email: "careers@emitac.ae" },
  { name: "GBM (Gulf Business Machines)", type: "IT Solutions", email: "careers@gbmme.com" },
  { name: "CNS (Computer Network Systems)", type: "System Integrator", email: "careers@cns-me.com" },
  { name: "Injazat", type: "Digital Transformation", email: "careers@injazat.com" },
  { name: "Moro Hub", type: "Cloud Services", email: "careers@morohub.com" },
  { name: "Starzplay", type: "Media Tech", email: "careers@starzplay.com" },
  { name: "Huspy", type: "PropTech / Fintech", email: "careers@huspy.com" },
  { name: "Sarwa", type: "Fintech", email: "careers@sarwa.co" },
  { name: "BitOasis", type: "Fintech / Crypto", email: "careers@bitoasis.net" },
  { name: "Yallacompare", type: "Fintech", email: "careers@yallacompare.com" },
  { name: "ServiceMarket", type: "Online Marketplace", email: "careers@servicemarket.com" },
  { name: "JustLife", type: "Home Services Tech", email: "careers@justlife.com" },
  { name: "InstaShop", type: "Q-Commerce", email: "careers@instashop.com" },
  { name: "Anghami", type: "Music Streaming / Tech", email: "careers@anghami.com" },
  { name: "Vezeeta", type: "HealthTech", email: "careers@vezeeta.com" },
  { name: "Eyewa", type: "E-commerce / Retail Tech", email: "careers@eyewa.com" },
  { name: "TruKKer", type: "Logistics Tech", email: "careers@trukker.com" },
  { name: "Ziina", type: "Fintech", email: "careers@ziina.com" },
  { name: "Dataiku", type: "AI / Software", email: "careers@dataiku.com" },
  { name: "Fireflies.ai", type: "AI / SaaS", email: "careers@fireflies.ai" },
  { name: "Flare Network", type: "Blockchain / Crypto", email: "info@flare.network" },
  { name: "MongoDB", type: "Software / Database", email: "careers@mongodb.com" },
  { name: "Arada", type: "Real Estate Tech", email: "careers@arada.com" },
  { name: "Masdar (Tech Division)", type: "Clean Tech", email: "careers@masdar.ae" },
  { name: "Qashio", type: "Fintech", email: "careers@qashio.com" },
  { name: "MYCRANE", type: "Logistics Tech", email: "info@mycrane.com" },
  { name: "CredibleX", type: "Fintech", email: "info@crediblex.com" },
  { name: "Tarabut Gateway", type: "Fintech / Open Banking", email: "careers@tarabutgateway.com" },
  { name: "Holo", type: "Fintech / Mortgage Tech", email: "careers@holo.ae" },
  { name: "Beehive", type: "Fintech / P2P Lending", email: "team@beehive.ae" },
  { name: "qlub", type: "Fintech / Payments", email: "careers@qlub.io" },
  { name: "WheelsOn", type: "Mobility Tech", email: "info@wheelson.com" },
  { name: "Five Holdings", type: "Hospitality Tech", email: "careers@fivehotelsandresorts.com" },
  { name: "Omniyat", type: "Real Estate Tech", email: "careers@omniyat.com" },
  { name: "Stake", type: "Fintech / Real Estate", email: "contact@getstake.com" },
  { name: "Fuze", type: "Crypto Infrastructure", email: "careers@fuze.finance" },
  { name: "Alaan", type: "Fintech / Spend Management", email: "careers@alaan.com" },
  { name: "AMEA Power", type: "Energy Tech", email: "info@ameapower.com" },
  { name: "Khazna", type: "Data Center", email: "careers@khazna.ae" },
  { name: "XPANCEO", type: "Deep Tech / AR", email: "careers@xpanceo.com" },
  { name: "The Binary Holdings", type: "Web3 / Infrastructure", email: "info@thebinaryholdings.com" },
  { name: "Rihal", type: "Data / AI", email: "info@rihal.om" },
  { name: "Astra Tech", type: "Consumer Tech", email: "careers@astratech.ae" },
  { name: "B2Broker", type: "Fintech / Crypto", email: "careers@b2broker.com" },
  { name: "DP World (Tech Division)", type: "Logistics Tech", email: "careers@dpworld.com" },
  { name: "Yellow Door Energy", type: "Clean Tech", email: "careers@yellowdoorenergy.com" },
  { name: "Telr", type: "Fintech / Payments", email: "careers@telr.com" },
  { name: "Octa", type: "Fintech", email: "info@octa.ae" },
  { name: "LowKick Studio", type: "Gaming", email: "jobs@lowkick-studio.com" },
  { name: "Fasset", type: "Fintech / Crypto", email: "careers@fasset.com" },
  { name: "Keyper", type: "PropTech", email: "careers@realkeyper.com" },
  { name: "iMile", type: "Logistics Tech", email: "careers@imile.com" },
  { name: "ArabyAds", type: "AdTech", email: "careers@arabyads.com" },
  { name: "Symbiotic", type: "Tech", email: "info@symbiotic.fi" },
  { name: "Alpheya", type: "Fintech", email: "info@alpheya.com" },
  { name: "Deem Finance", type: "Fintech", email: "careers@deem.io" },
  { name: "Biptap", type: "Fintech", email: "info@biptap.com" },
  { name: "SmartCrowd", type: "Fintech / Real Estate", email: "careers@smartcrowd.ae" },
  { name: "Qarrib", type: "Marketplace", email: "info@qarrib.com" },
  { name: "LandRocker", type: "Gaming / Web3", email: "info@landrocker.io" },
  { name: "NexGen", type: "IT Services", email: "info@nexgen.ae" },
  { name: "Adam Global", type: "Consulting / IT", email: "hr@adamglobal.com" },
  { name: "Right ERP", type: "ERP Solutions", email: "info@righterp.com" },
  { name: "Accent Infotech", type: "IT Services", email: "jobs@accentinfotech.com" },
  { name: "Dolphin UAE", type: "IT Solutions", email: "hr@dolphinuae.com" },
  { name: "Sabson Dubai", type: "IT Services", email: "hr@sabsondubai.com" },
  { name: "Arch Corp", type: "Engineering Tech", email: "careers@archcorp.biz" },
  { name: "Bates PanGulf", type: "Digital Agency", email: "careers@batespangulf.com" },
  { name: "Cyber Services", type: "Cybersecurity", email: "hr.zetech@cyberservices.com" },
  { name: "Haroon Co", type: "IT Trading", email: "hr@haroonco.com" },
  { name: "Specialist Group", type: "IT Recruitment", email: "HR@SpecialistGroup.com" },
  { name: "Pancrop", type: "Software", email: "hire@pancrop.com" },
  { name: "Mermaid Digital", type: "Digital Marketing/IT", email: "hrdubai@mermaiddigital.com" },
  { name: "Pact Employment", type: "IT Staffing", email: "info@pactemployment.ae" },
  { name: "Mega Power LLC", type: "IT Infrastructure", email: "hr@megapowerllc.com" },
  { name: "Satguru Travel (Tech Team)", type: "Travel Tech", email: "hr@satgurutravel.com" },
  { name: "Hira Solutions", type: "IT Solutions", email: "career@hirasolutions.com" },
  { name: "Stable Force", type: "IT Services", email: "hr@stableforceuae.com" },
  { name: "Eng UAE", type: "Engineering Software", email: "recruitment_officer@enguae.com" },
  { name: "Golden Swan Group", type: "General Trading/IT", email: "hr@goldenswangroup.com" },
  { name: "Emitac", type: "IT Solutions", email: "support_dxb@emitac.ae" },
  { name: "Redington Gulf", type: "IT Distribution", email: "abudhabi.service@redingtongulf.com" },
  { name: "Axiom Telecom", type: "Telecom/Tech", email: "support@axiomtelecom.com" },
  { name: "Jacky's Electronics", type: "Retail Tech", email: "sales@jackys.com" },
  { name: "Sharaf DG (Tech)", type: "Retail Tech", email: "eretail.admin@sharafdg.com" },
  { name: "Canon Middle East", type: "Imaging Tech", email: "gina.jones@canon-europe.com" },
  { name: "Al Sayegh Media", type: "Digital Media", email: "info@alsayeghmedia.com" },
  { name: "Prism Middle East", type: "Digital Agency", email: "info@prism-me.com" },
  { name: "Aramex (Tech Team)", type: "Logistics Tech", email: "DXBHR-Recruitment@aramex.com" },
  { name: "Best Focus", type: "IT Services", email: "office@bestfocus.net" },
  { name: "Integrity", type: "IT Solutions", email: "info@integrity.ae" },
  { name: "Innovation UAE", type: "Tech Solutions", email: "info@innovationuae.com" },
  { name: "Zad Solutions", type: "Software Development", email: "hr@zadsolutions.com" },
  { name: "Wallstreet Exchange (Tech)", type: "Fintech", email: "apply@wallstreet.ae" },
  { name: "UAE Exchange (Tech)", type: "Fintech", email: "he.recruit@uaeexchange.com" },
  { name: "AIWA Digital", type: "Digital Transformation", email: "info@aiwadigital.com" },
  { name: "Shubbak Technologies", type: "Software Development", email: "info@shubbak.ae" },
  { name: "Sigma Solutions", type: "Software Solutions", email: "info@sigmasolutions.ae" },
  { name: "Tech Karobar", type: "IT Services", email: "info@techkarobar.com" },
  { name: "Ubitech", type: "Software / IT", email: "info@ubitech.ae" },
  { name: "Qorden AI", type: "AI Solutions", email: "info@qorden.ai" },
  { name: "Promide Computer Technology", type: "IT Services", email: "info@promide.com" },
  { name: "Medas Middle East", type: "Healthcare IT", email: "info@medas.ae" },
  { name: "System Berries Technologies", type: "Software Development", email: "info@systemberries.com" },
  { name: "Dahua Technology", type: "Security Tech", email: "info@dahuasecurity.com" },
  { name: "Infotiz Solutions", type: "IT Consultancy", email: "info@infotiz.com" },
  { name: "Emircom", type: "System Integrator", email: "info@emircom.com" },
  { name: "Pentagram Solutions", type: "IT Solutions", email: "info@pentagram.ae" },
  { name: "Prologix", type: "IT/Security", email: "info@prologixdistribution.com" },
  { name: "Netway Solutions", type: "IT/Networking", email: "info@netwaysolutions.com" },
  { name: "ALHD Information Technology", type: "Software", email: "info@alhd.ae" },
  { name: "Power Interactive", type: "IT Services", email: "info@powerinteractive.ae" },
  { name: "24 Frames Digital", type: "Digital Media", email: "info@24frames.ae" },
  { name: "3i-Infotech", type: "IT Services", email: "careers@3i-infotech.com" },
  { name: "3M Brothers for Computer", type: "Hardware/IT", email: "info@3mbrothers.com" },
  { name: "3S System", type: "IT Solutions", email: "info@3ssystem.com" },
  { name: "3SC Technologies", type: "IT Services", email: "info@3sc.ae" },
  { name: "4 Power Infocom", type: "IT Services", email: "info@4power.ae" },
  { name: "4 Sight Technology", type: "IT Consulting", email: "info@4sight.ae" },
  { name: "Sage Software Middle East", type: "ERP Software", email: "careersme@sage.com" },
  { name: "eHosting Datafort", type: "Cloud / Hosting", email: "info@ehdf.com" },
  { name: "Vision Solution", type: "IT Solutions", email: "info@visionsolution.ae" },
  { name: "Netcure", type: "Cybersecurity", email: "info@netcure.ae" },
  { name: "RAS Infotech", type: "IT Security", email: "info@rasinfotech-dubai.com" },
  { name: "Paramount Computer Systems", type: "Cybersecurity", email: "info@paramountassure.com" },
  { name: "Javelin Communications", type: "IT Services", email: "info@javelin.ae" },
  { name: "Mavaj Sun Co", type: "Web Development", email: "info@mavajsun.com" },
  { name: "Fidobe Solutions", type: "ERP / Accounting Software", email: "info@fidobe.com" },
  { name: "Ducont Systems", type: "Mobile App / AI", email: "careers@ducont.com" },
  { name: "Avenues World", type: "E-commerce Solutions", email: "info@avenues.ae" },
  { name: "Mindtree (LTIMindtree)", type: "IT Consulting", email: "careers@ltimindtree.com" },
  { name: "Wipro", type: "IT Services", email: "careers@wipro.com" },
  { name: "TCS (Tata Consultancy Services)", type: "IT Services", email: "careers@tcs.com" },
  { name: "Infosys", type: "IT Consulting", email: "careers@infosys.com" },
  { name: "HCLTech", type: "IT Services", email: "careers@hcltech.com" },
  { name: "Tech Mahindra", type: "IT Services", email: "careers@techmahindra.com" },
  { name: "IBM Middle East", type: "Technology / Cloud", email: "careers@ibm.com" },
  { name: "Microsoft UAE", type: "Technology", email: "careers@microsoft.com" },
  { name: "Google UAE", type: "Technology", email: "careers@google.com" },
  { name: "Oracle Middle East", type: "Cloud / Software", email: "careers@oracle.com" },
  { name: "SAP MENA", type: "Enterprise Software", email: "careers@sap.com" },
  { name: "Cisco Middle East", type: "Networking / IT", email: "careers@cisco.com" },
  { name: "Dell Technologies", type: "Hardware / Cloud", email: "careers@dell.com" },
  { name: "HP Inc.", type: "Hardware / IT", email: "careers@hp.com" },
  { name: "Honeywell Middle East", type: "Industrial Tech", email: "careers@honeywell.com" },
  { name: "Siemens Digital Industries", type: "Industrial Software", email: "careers@siemens.com" },
  { name: "Schneider Electric", type: "Energy Tech", email: "careers@se.com" },
  { name: "Huawei Middle East", type: "Telecom / Tech", email: "careers@huawei.com" },
  { name: "Nokia", type: "Telecom", email: "careers@nokia.com" },
  { name: "Ericsson", type: "Telecom", email: "careers@ericsson.com" },
  { name: "Accenture Middle East", type: "Consulting / Tech", email: "careers@accenture.com" },
  { name: "PwC Middle East (Tech)", type: "Consulting", email: "careers@pwc.com" },
  { name: "Deloitte (Digital)", type: "Consulting", email: "careers@deloitte.com" },
  { name: "KPMG Lower Gulf (Tech)", type: "Consulting", email: "careers@kpmg.com" },
  { name: "EY MENA (Tech)", type: "Consulting", email: "careers@ey.com" },
  { name: "Capgemini", type: "IT Consulting", email: "careers@capgemini.com" },
  { name: "Atos", type: "Digital Transformation", email: "careers@atos.net" },
  { name: "DXC Technology", type: "IT Services", email: "careers@dxc.com" },
  { name: "Kyndryl", type: "IT Infrastructure", email: "careers@kyndryl.com" },
  { name: "Cognizant", type: "IT Services", email: "careers@cognizant.com" },
  { name: "Thoughtworks", type: "Software Consultancy", email: "careers@thoughtworks.com" },
  { name: "Publicis Sapient", type: "Digital Transformation", email: "careers@publicissapient.com" },
  { name: "Instinctools", type: "Software Development", email: "careers@instinctools.com" },
  { name: "SDLC Corp", type: "Software Development", email: "careers@sdlccorp.com" },
  { name: "Tallium Inc", type: "Software Development", email: "careers@tallium.com" },
  { name: "STS Software", type: "Software Development", email: "careers@sts.com" },
  { name: "Techunting America (UAE Branch)", type: "IT Staffing", email: "careers@techunting.com" },
  { name: "SELISE Group", type: "IT Delivery", email: "careers@selise.ch" },
  { name: "LeverX", type: "SAP Solutions", email: "careers@leverx.com" },
  { name: "Probey Services", type: "IT Services", email: "careers@probey.com" },
  { name: "Suffescom Solutions", type: "Software Development", email: "careers@suffescom.com" },
  { name: "Magneto IT Solutions", type: "E-commerce Dev", email: "careers@magnetoitsolutions.com" },
  { name: "CSSChopper", type: "Web Development", email: "careers@csschopper.com" },
  { name: "Kuchoriya Techsoft", type: "Software Development", email: "careers@kuchoriya.com" },
  { name: "Simform", type: "Product Engineering", email: "careers@simform.com" },
  { name: "Aristek Systems", type: "EdTech / HealthTech", email: "careers@aristek.com" },
  { name: "Plaxonic Technologies", type: "AI / Automation", email: "careers@plaxonic.com" },
  { name: "DICEUS", type: "Insurance Tech", email: "careers@diceus.com" },
  { name: "Codiant", type: "Mobile Apps", email: "careers@codiant.com" },
  { name: "MoogleLabs", type: "AI / Blockchain", email: "careers@mooglelabs.com" },
  { name: "Quixta", type: "Web Design", email: "careers@quixta.com" },
  { name: "MMC Global", type: "Software Development", email: "careers@mmcglobal.com" },
  { name: "SISGAIN", type: "Healthcare IT", email: "careers@sisgain.ae" },
  { name: "Apptunix", type: "Mobile Apps", email: "careers@apptunix.com" },
  { name: "Quicworks", type: "ERP / Automation", email: "careers@quicworks.com" },
  { name: "Webisoft", type: "Blockchain", email: "careers@webisoft.com" },
  { name: "InovarTech Solutions", type: "AI / IoT", email: "careers@inovartech.com" },
  { name: "Blue.Me", type: "App Development", email: "careers@blue.me" },
  { name: "Unbox", type: "Digital Agency", email: "careers@unbox.agency" },
  { name: "Red Spider", type: "Web Design", email: "info@redspider.ae" },
  { name: "Go-Gulf", type: "Web Development", email: "careers@go-gulf.com" },
  { name: "Global Media Insight", type: "Digital Agency", email: "careers@globalmediainsight.com" },
  { name: "Branex", type: "Web Design / App Dev", email: "careers@branex.ae" },
  { name: "Element 8", type: "Digital Agency", email: "info@element8.ae" },
  { name: "Traffic Digital", type: "Digital Agency", email: "careers@wewanttraffic.com" },
  { name: "Nexa", type: "Digital Marketing / Tech", email: "careers@digitalnexa.com" },
  { name: "Chain Reaction", type: "Digital Performance", email: "careers@chainreaction.ae" },
  { name: "EDS (Emirates Digital Solutions)", type: "IT Services", email: "info@eds.ae" },
  { name: "Royex Technologies", type: "Mobile App / E-commerce", email: "careers@royex.com" },
  { name: "Xicom Technologies", type: "Software Development", email: "careers@xicom.ae" },
  { name: "Code & Co", type: "Web Development", email: "careers@codeandco.com" },
  { name: "Fugro (Tech Division)", type: "Geo-data / Tech", email: "careers@fugro.com" },
  { name: "Bayanat", type: "Geospatial AI", email: "careers@bayanat.ai" },
  { name: "Help AG", type: "Cybersecurity", email: "careers@helpag.com" },
  { name: "Bespin Global", type: "Cloud Consulting", email: "careers@bespinglobal.com" },
  { name: "BIOS Middle East", type: "Cloud Services", email: "careers@biosme.com" },
  { name: "e& enterprise", type: "Digital Solutions", email: "careers@eand.com" },
  { name: "Khaleej Times (Tech Team)", type: "Media Tech", email: "careers@khaleejtimes.com" },
  { name: "Gulf News (Tech Team)", type: "Media Tech", email: "careers@gulfnews.com" },
  { name: "MBC Group (Tech)", type: "Media Tech", email: "careers@mbc.net" },
  { name: "OSN (Tech Team)", type: "Media Tech", email: "careers@osn.com" },
  { name: "Rotana (Tech Team)", type: "Media Tech", email: "careers@rotana.net" },
  { name: "Majid Al Futtaim (Tech/Carrefour)", type: "Retail Tech", email: "careers@majidalfuttaim.com" },
  { name: "Landmark Group (Tech)", type: "Retail Tech", email: "careers@landmarkgroup.com" },
  { name: "Chalhoub Group (Tech)", type: "Retail Tech", email: "careers@chalhoubgroup.com" },
  { name: "Al Tayer Group (Tech)", type: "Retail Tech", email: "careers@altayer.com" },
  { name: "Al-Futtaim Group (Tech)", type: "Conglomerate Tech", email: "careers@alfuttaim.com" },
  { name: "GEMS Education (Tech)", type: "EdTech", email: "careers@gemseducation.com" },
  { name: "Aster DM Healthcare (Tech)", type: "HealthTech", email: "careers@asterdmhealthcare.com" },
  { name: "NMC Healthcare (Tech)", type: "HealthTech", email: "careers@nmc.ae" },
  { name: "Mediclinic Middle East (Tech)", type: "HealthTech", email: "careers@mediclinic.ae" },
  { name: "Cleveland Clinic Abu Dhabi (Tech)", type: "HealthTech", email: "careers@clevelandclinicabudhabi.ae" },
  { name: "Emirates Airline (IT)", type: "Aviation Tech", email: "careers@emirates.com" },
  { name: "Etihad Airways (IT)", type: "Aviation Tech", email: "careers@etihad.com" },
  { name: "Flydubai (IT)", type: "Aviation Tech", email: "careers@flydubai.com" },
  { name: "Air Arabia (IT)", type: "Aviation Tech", email: "careers@airarabia.com" },
  { name: "Dubai Airports (IT)", type: "Aviation Tech", email: "careers@dubaiairports.ae" },
  { name: "Abu Dhabi Airports (IT)", type: "Aviation Tech", email: "careers@adairports.ae" },
  { name: "ADCB (Tech)", type: "Banking Tech", email: "careers@adcb.com" },
  { name: "Emirates NBD (Tech)", type: "Banking Tech", email: "careers@emiratesnbd.com" },
  { name: "FAB (First Abu Dhabi Bank) Tech", type: "Banking Tech", email: "careers@bankfab.com" },
  { name: "Dubai Islamic Bank (Tech)", type: "Banking Tech", email: "careers@dib.ae" },
  { name: "Mashreq Bank (Tech)", type: "Banking Tech", email: "careers@mashreq.com" },
  { name: "RAKNUM", type: "Fintech / Banking", email: "careers@rakbank.ae" },
  { name: "Commercial Bank of Dubai (Tech)", type: "Banking Tech", email: "careers@cbd.ae" },
  { name: "Abu Dhabi Islamic Bank (Tech)", type: "Banking Tech", email: "careers@adib.ae" },
  { name: "HSBC UAE (Tech)", type: "Banking Tech", email: "careers@hsbc.com" },
  { name: "Standard Chartered UAE (Tech)", type: "Banking Tech", email: "careers@sc.com" },
  { name: "Citibank UAE (Tech)", type: "Banking Tech", email: "careers@citi.com" },
  { name: "Visa Middle East", type: "Payments Tech", email: "careers@visa.com" },
  { name: "Mastercard Middle East", type: "Payments Tech", email: "careers@mastercard.com" },
  { name: "Network International", type: "Payments Tech", email: "careers@network.ae" },
  { name: "Checkout.com (UAE)", type: "Fintech", email: "careers@checkout.com" },
  { name: "Stripe (UAE)", type: "Fintech", email: "careers@stripe.com" },
  { name: "Adyen (UAE)", type: "Fintech", email: "careers@adyen.com" },
  { name: "PayPal (UAE)", type: "Fintech", email: "careers@paypal.com" },
  { name: "Careem Pay", type: "Fintech", email: "careers@careem.com" },
  { name: "PayTabs", type: "Fintech", email: "careers@paytabs.com" },
  { name: "Telr", type: "Payment Gateway", email: "careers@telr.com" },
  { name: "HyperPay", type: "Fintech", email: "careers@hyperpay.com" },
  { name: "Geidea", type: "Fintech", email: "careers@geidea.net" },
  { name: "Tap Payments", type: "Fintech", email: "careers@tap.company" },
  { name: "Mamopay", type: "Fintech", email: "careers@mamopay.com" },
  { name: "Ziina", type: "Peer-to-Peer Payments", email: "careers@ziina.com" },
  { name: "Baraka", type: "Fintech / Investing", email: "careers@getbaraka.com" },
  { name: "Sarwa", type: "Robo-Advisor", email: "careers@sarwa.co" },
  { name: "StashAway", type: "Fintech", email: "careers@stashaway.ae" },
  { name: "Hala", type: "InsureTech", email: "careers@hala.com" },
  { name: "BuyAnyInsurance", type: "InsureTech", email: "careers@buyanyinsurance.com" },
  { name: "Yallacompare", type: "Comparison Platform", email: "careers@yallacompare.com" },
  { name: "InsuranceMarket.ae", type: "InsureTech", email: "careers@insurancemarket.ae" },
  { name: "Policybazaar UAE", type: "InsureTech", email: "careers@policybazaar.ae" },
  { name: "Bayzat", type: "HR & Insurance Tech", email: "careers@bayzat.com" },
  { name: "Swan", type: "E-commerce / Lifestyle", email: "careers@swan.shop" },
  { name: "InstaShop", type: "Grocery Tech", email: "careers@instashop.com" },
  { name: "El Grocer", type: "Grocery Tech", email: "careers@elgrocer.com" },
  { name: "Kibsons (Tech)", type: "E-commerce", email: "careers@kibsons.com" },
  { name: "Deliveroo UAE", type: "Food Tech", email: "careers@deliveroo.ae" },
  { name: "Zomato UAE", type: "Food Tech", email: "careers@zomato.com" },
  { name: "Cari", type: "Food Tech", email: "careers@getcari.com" },
  { name: "EatEasy", type: "Food Tech", email: "careers@eateasy.ae" },
  { name: "Snoonu", type: "Tech / Delivery", email: "careers@snoonu.com" },
  { name: "Cafu", type: "Fuel Delivery Tech", email: "careers@cafu.com" },
  { name: "JustLife", type: "Home Services App", email: "careers@justlife.com" },
  { name: "Urban Company UAE", type: "Home Services Tech", email: "careers@urbancompany.com" },
  { name: "Washmen", type: "Laundry Tech", email: "careers@washmen.com" },
  { name: "Laundryheap UAE", type: "Laundry Tech", email: "careers@laundryheap.com" },
  { name: "ServiceMarket", type: "Home Services Marketplace", email: "careers@servicemarket.com" },
  { name: "Rizek", type: "Service Marketplace", email: "careers@rizek.com" },
  { name: "Dubizzle", type: "Classifieds", email: "careers@dubizzle.com" },
  { name: "Property Finder", type: "Real Estate Portal", email: "careers@propertyfinder.ae" },
  { name: "Bayut", type: "Real Estate Portal", email: "careers@bayut.com" },
  { name: "Houza", type: "Real Estate Portal", email: "careers@houza.com" },
  { name: "Wasl (Tech)", type: "Real Estate Tech", email: "careers@wasl.ae" },
  { name: "Emaar (Tech)", type: "Real Estate Tech", email: "careers@emaar.com" },
  { name: "Damac (Tech)", type: "Real Estate Tech", email: "careers@damacproperties.com" },
  { name: "Nakheel (Tech)", type: "Real Estate Tech", email: "careers@nakheel.com" },
  { name: "Meraas (Tech)", type: "Real Estate Tech", email: "careers@meraas.ae" },
  { name: "Dubai Holding (Tech)", type: "Conglomerate Tech", email: "careers@dubaiholding.com" },
  { name: "TECOM Group", type: "Business Parks / Tech", email: "careers@tecomgroup.ae" },
  { name: "DIFC (Tech)", type: "Financial Centre Tech", email: "careers@difc.ae" },
  { name: "ADGM (Tech)", type: "Financial Centre Tech", email: "careers@adgm.com" },
  { name: "DMCC (Tech)", type: "Free Zone Tech", email: "careers@dmcc.ae" },
  { name: "Jafza (Tech)", type: "Free Zone Tech", email: "careers@jafza.ae" },
  { name: "DAFZA (Tech)", type: "Free Zone Tech", email: "careers@dafza.ae" },
  { name: "RAKEZ (Tech)", type: "Free Zone Tech", email: "careers@rakez.com" },
  { name: "Shams (Tech)", type: "Free Zone Tech", email: "careers@shams.ae" },
  { name: "Twofour54", type: "Media Tech Zone", email: "careers@twofour54.com" },
  { name: "Dubai Internet City", type: "Tech Hub", email: "info@dic.ae" },
  { name: "Dubai Silicon Oasis", type: "Tech Park", email: "info@dsoa.ae" },
  { name: "Hub71", type: "Tech Ecosystem", email: "careers@hub71.com" },
  { name: "Dtec", type: "Tech Entrepreneur Centre", email: "info@dtec.ae" },
  { name: "Sheraa", type: "Entrepreneurship Center", email: "info@sheraa.ae" },
  { name: "StartAD", type: "Startup Accelerator", email: "startad@nyu.edu" },
  { name: "Plug and Play AD", type: "Accelerator", email: "careers@plugandplaybox.com" },
  { name: "Flat6Labs UAE", type: "Accelerator", email: "careers@flat6labs.com" },
  { name: "AstroLabs", type: "Tech Ecosystem", email: "careers@astrolabs.com" },
  { name: "In5", type: "Innovation Centre", email: "info@in5.ae" },
  { name: "Kryptolabs", type: "Crypto Hub", email: "info@kryptolabs.com" },
  { name: "Block71", type: "Tech Ecosystem", email: "abudhabi@block71.co" },
  { name: "Area 2071", type: "Innovation Hub", email: "hello@area2071.ae" },
  { name: "Museum of the Future (Tech)", type: "Innovation", email: "info@museumofthefuture.ae" },
  { name: "Expo City Dubai (Tech)", type: "Innovation", email: "careers@expocitydubai.com" },
  { name: "Bee'ah (Tech)", type: "Sustainability Tech", email: "careers@beeahgroup.com" },
  { name: "Masdar City (Tech)", type: "Sustainability Tech", email: "careers@masdarcity.ae" },
  { name: "Shurooq (Tech)", type: "Development Tech", email: "careers@shurooq.gov.ae" },
  { name: "Mubadala (Tech Investment)", type: "Investment Tech", email: "careers@mubadala.ae" },
  { name: "ADQ (Tech Investment)", type: "Investment Tech", email: "careers@adq.ae" },
  { name: "Investment Corporation of Dubai", type: "Investment Tech", email: "careers@icd.gov.ae" },
  { name: "Dubai Future Foundation", type: "Future Tech", email: "careers@dubaifuture.gov.ae" },
  { name: "Smart Dubai", type: "GovTech", email: "careers@smartdubai.ae" },
  { name: "RTA (Tech Division)", type: "Transport Tech", email: "careers@rta.ae" },
  { name: "DEWA (Tech Division)", type: "Utility Tech", email: "careers@dewa.gov.ae" },
  { name: "Dubai Police (AI Department)", type: "Security Tech", email: "mail@dubaipolice.gov.ae" },
  { name: "Abu Dhabi Police (Tech)", type: "Security Tech", email: "careers@adpolice.gov.ae" },
  { name: "Ministry of AI", type: "GovTech", email: "info@ai.gov.ae" },
  { name: "TRA (TDRA)", type: "GovTech", email: "careers@tdra.gov.ae" },
  { name: "Nazzar", type: "AR/VR", email: "info@nazzar.ae" },
  { name: "Takeleap", type: "VR/AR", email: "info@takeleap.com" },
  { name: "Pixelbug", type: "AR/VR", email: "info@pixelbug.com" },
  { name: "Giga Works", type: "VR/AR", email: "info@gigaworks.ae" },
  { name: "Visual Experience", type: "VR/AR", email: "info@visualexperience.ae" },
  { name: "Jivox", type: "Digital Marketing Tech", email: "careers@jivox.com" },
  { name: "Medialogic", type: "Media Tech", email: "careers@medialogicdubai.com" },
  { name: "Travelport UAE", type: "Travel Tech", email: "careers@travelport.com" },
  { name: "Amadeus UAE", type: "Travel Tech", email: "careers@amadeus.com" },
  { name: "Sabre UAE", type: "Travel Tech", email: "careers@sabre.com" },
  { name: "dnata (Tech)", type: "Travel Services", email: "careers@dnata.com" },
  { name: "Musafir.com", type: "Travel Tech", email: "careers@musafir.com" },
  { name: "Rehlat", type: "Travel Tech", email: "careers@rehlat.com" },
  { name: "HolidayMe", type: "Travel Tech", email: "careers@holidayme.com" },
  { name: "Tajawal", type: "Travel Tech", email: "careers@tajawal.com" },
  { name: "Almosafer", type: "Travel Tech", email: "careers@almosafer.com" },
  { name: "Cobone", type: "Deals / E-commerce", email: "careers@cobone.com" },
  { name: "Groupon UAE", type: "Deals / E-commerce", email: "careers@groupon.ae" },
  { name: "The Entertainer", type: "Lifestyle App", email: "careers@theentertainerme.com" },
  { name: "Pricena", type: "Comparison / Tech", email: "careers@pricena.com" },
  { name: "Kanari", type: "Customer Experience Tech", email: "careers@kanari.com" },
  { name: "Unifonic", type: "Cloud Comms", email: "careers@unifonic.com" },
  { name: "Cequens", type: "Cloud Comms", email: "careers@cequens.com" },
  { name: "Infobip UAE", type: "Cloud Comms", email: "careers@infobip.com" },
  { name: "Twilio (Remote/UAE)", type: "Cloud Comms", email: "careers@twilio.com" },
  { name: "MessageBird (UAE)", type: "Cloud Comms", email: "careers@messagebird.com" },
  { name: "Zoho (UAE)", type: "SaaS", email: "careers@zohocorp.com" },
  { name: "Freshworks (UAE)", type: "SaaS", email: "careers@freshworks.com" },
  { name: "Salesforce (UAE)", type: "SaaS / CRM", email: "careers@salesforce.com" },
  { name: "ServiceNow (UAE)", type: "SaaS / ITSM", email: "careers@servicenow.com" },
  { name: "Workday (UAE)", type: "SaaS / HR", email: "careers@workday.com" },
  { name: "Atlassian (Partners)", type: "SaaS / DevOps", email: "careers@atlassian.com" },
  { name: "VMware (UAE)", type: "Cloud Infrastructure", email: "careers@vmware.com" },
  { name: "Red Hat (UAE)", type: "Open Source / Cloud", email: "careers@redhat.com" },
  { name: "Citrix (UAE)", type: "Cloud / Virtualization", email: "careers@citrix.com" },
  { name: "Nutanix (UAE)", type: "Cloud Computing", email: "careers@nutanix.com" },
  { name: "Snowflake (UAE)", type: "Data Cloud", email: "careers@snowflake.com" },
  { name: "Databricks (UAE)", type: "Data / AI", email: "careers@databricks.com" },
  { name: "Palantir (UAE)", type: "Big Data", email: "careers@palantir.com" },
  { name: "Splunk (UAE)", type: "Data / Security", email: "careers@splunk.com" },
  { name: "Elastic (UAE)", type: "Search / Data", email: "careers@elastic.co" },
  { name: "Trend Micro (UAE)", type: "Cybersecurity", email: "careers@trendmicro.com" },
  { name: "Fortinet (UAE)", type: "Cybersecurity", email: "careers@fortinet.com" },
  { name: "Palo Alto Networks (UAE)", type: "Cybersecurity", email: "careers@paloaltonetworks.com" },
  { name: "Check Point (UAE)", type: "Cybersecurity", email: "careers@checkpoint.com" },
  { name: "FireEye (Trellix) UAE", type: "Cybersecurity", email: "careers@trellix.com" },
  { name: "CrowdStrike (UAE)", type: "Cybersecurity", email: "careers@crowdstrike.com" },
  { name: "Sophos (UAE)", type: "Cybersecurity", email: "careers@sophos.com" },
  { name: "Kaspersky (UAE)", type: "Cybersecurity", email: "careers@kaspersky.com" },
  { name: "ESET (UAE)", type: "Cybersecurity", email: "careers@eset.com" },
  { name: "Mimecast (UAE)", type: "Cybersecurity", email: "careers@mimecast.com" },
  { name: "Proofpoint (UAE)", type: "Cybersecurity", email: "careers@proofpoint.com" },
  { name: "Zscaler (UAE)", type: "Cybersecurity", email: "careers@zscaler.com" },
  { name: "Okta (UAE)", type: "Identity Security", email: "careers@okta.com" },
  { name: "CyberArk (UAE)", type: "Identity Security", email: "careers@cyberark.com" },
  { name: "SailPoint (UAE)", type: "Identity Security", email: "careers@sailpoint.com" },
  { name: "BeyondTrust (UAE)", type: "Identity Security", email: "careers@beyondtrust.com" },
  { name: "Tenable (UAE)", type: "Cyber Exposure", email: "careers@tenable.com" },
  { name: "Qualys (UAE)", type: "Security Compliance", email: "careers@qualys.com" },
  { name: "Rapid7 (UAE)", type: "Security Analytics", email: "careers@rapid7.com" },
  { name: "SolarWinds (UAE)", type: "IT Management", email: "careers@solarwinds.com" },
  { name: "ManageEngine (UAE)", type: "IT Management", email: "careers@manageengine.com" },
  { name: "Paessler (PRTG) UAE", type: "Network Monitoring", email: "careers@paessler.com" },
  { name: "Veeam (UAE)", type: "Data Backup", email: "careers@veeam.com" },
  { name: "Commvault (UAE)", type: "Data Management", email: "careers@commvault.com" },
  { name: "Veritas (UAE)", type: "Data Protection", email: "careers@veritas.com" },
  { name: "Rubrik (UAE)", type: "Data Security", email: "careers@rubrik.com" },
  { name: "Cohesity (UAE)", type: "Data Management", email: "careers@cohesity.com" },
  { name: "Pure Storage (UAE)", type: "Storage", email: "careers@purestorage.com" },
  { name: "NetApp (UAE)", type: "Storage / Cloud", email: "careers@netapp.com" },
  { name: "Hitachi Vantara (UAE)", type: "Data / Storage", email: "careers@hitachivantara.com" },
  { name: "Western Digital (UAE)", type: "Storage", email: "careers@westerndigital.com" },
  { name: "Seagate (UAE)", type: "Storage", email: "careers@seagate.com" },
  { name: "Intel (UAE)", type: "Semiconductor", email: "careers@intel.com" },
  { name: "AMD (UAE)", type: "Semiconductor", email: "careers@amd.com" },
  { name: "NVIDIA (UAE)", type: "AI Computing", email: "careers@nvidia.com" },
  { name: "Qualcomm (UAE)", type: "Semiconductor / Telecom", email: "careers@qualcomm.com" },
  { name: "Broadcom (UAE)", type: "Semiconductor / Software", email: "careers@broadcom.com" },
  { name: "Samsung (UAE)", type: "Electronics / Tech", email: "careers@samsung.com" },
  { name: "LG Electronics (UAE)", type: "Electronics / Tech", email: "careers@lge.com" },
  { name: "Sony Middle East", type: "Electronics / Tech", email: "careers@sony-mea.com" },
  { name: "Panasonic (UAE)", type: "Electronics / Tech", email: "careers@panasonic.com" },
  { name: "Sharp Middle East", type: "Electronics / Tech", email: "careers@sharp.ae" },
  { name: "Toshiba Gulf", type: "Electronics / Tech", email: "careers@toshibagulf.com" },
  { name: "Epson Middle East", type: "Printers / Tech", email: "careers@epson.ae" },
  { name: "Xerox (UAE)", type: "Document Tech", email: "careers@xerox.com" },
  { name: "Ricoh (UAE)", type: "Document Tech", email: "careers@ricoh.ae" },
  { name: "Konica Minolta (UAE)", type: "Document Tech", email: "careers@konicaminolta.com" },
  { name: "Brother (UAE)", type: "Electronics / Tech", email: "careers@brother.ae" },
  { name: "Jabra (UAE)", type: "Audio Tech", email: "careers@jabra.com" },
  { name: "Plantronics (Poly)", type: "Audio Tech", email: "careers@poly.com" },
  { name: "Logitech (UAE)", type: "Peripherals", email: "careers@logitech.com" },
  { name: "Belkin (UAE)", type: "Connectivity", email: "careers@belkin.com" },
  { name: "D-Link Middle East", type: "Networking", email: "careers@dlink-me.com" },
  { name: "TP-Link UAE", type: "Networking", email: "careers@tp-link.com" },
  { name: "Linksys (UAE)", type: "Networking", email: "careers@linksys.com" },
  { name: "Netgear (UAE)", type: "Networking", email: "careers@netgear.com" },
  { name: "Ubiquiti (UAE)", type: "Networking", email: "careers@ui.com" },
  { name: "Aruba Networks (HPE)", type: "Networking", email: "careers@arubanetworks.com" },
  { name: "Ruckus Networks", type: "Networking", email: "careers@commscope.com" },
  { name: "Extreme Networks", type: "Networking", email: "careers@extremenetworks.com" },
  { name: "Juniper Networks", type: "Networking", email: "careers@juniper.net" },
  { name: "F5 Networks", type: "Networking / Security", email: "careers@f5.com" },
  { name: "Riverbed", type: "Network Performance", email: "careers@riverbed.com" },
  { name: "Citrix", type: "Virtualization", email: "careers@citrix.com" },
  { name: "Gartner (UAE)", type: "IT Research", email: "careers@gartner.com" },
  { name: "IDC (UAE)", type: "IT Research", email: "careers@idc.com" },
  { name: "Forrester (UAE)", type: "IT Research", email: "careers@forrester.com" },
  { name: "Omdia (UAE)", type: "Tech Research", email: "careers@omdia.com" },
  { name: "Frost & Sullivan (UAE)", type: "Consulting / Research", email: "careers@frost.com" },
  { name: "Oliver Wyman (UAE)", type: "Consulting", email: "careers@oliverwyman.com" },
  { name: "Boston Consulting Group (BCG) Tech", type: "Consulting", email: "careers@bcg.com" },
  { name: "McKinsey & Company (Digital)", type: "Consulting", email: "careers@mckinsey.com" },
  { name: "Bain & Company (Tech)", type: "Consulting", email: "careers@bain.com" },
  { name: "Strategy& (Tech)", type: "Consulting", email: "careers@strategyand.pwc.com" },
  { name: "Kearney (Tech)", type: "Consulting", email: "careers@kearney.com" },
  { name: "Arthur D. Little (Tech)", type: "Consulting", email: "careers@adlittle.com" },
  { name: "Roland Berger (Tech)", type: "Consulting", email: "careers@rolandberger.com" },
  { name: "AlixPartners (Tech)", type: "Consulting", email: "careers@alixpartners.com" },
  { name: "FTI Consulting (Tech)", type: "Consulting", email: "careers@fticonsulting.com" },
  { name: "Protiviti (UAE)", type: "Consulting / Risk", email: "careers@protiviti.com" },
  { name: "Grant Thornton (Tech)", type: "Consulting", email: "careers@grantthornton.ae" },
  { name: "BDO UAE (Tech)", type: "Consulting", email: "careers@bdo.ae" },
  { name: "Crowe UAE (Tech)", type: "Consulting", email: "careers@crowe.ae" },
  { name: "Baker Tilly (Tech)", type: "Consulting", email: "careers@bakertilly.ae" },
  { name: "Mazars (Tech)", type: "Consulting", email: "careers@mazars.ae" },
  { name: "PKF UAE (Tech)", type: "Consulting", email: "careers@pkfuae.com" },
  { name: "Talent 500", type: "IT Recruitment", email: "careers@talent500.co" },
  { name: "Michael Page (Tech)", type: "Recruitment", email: "careers@michaelpage.ae" },
  { name: "Hays (Tech)", type: "Recruitment", email: "careers@hays.ae" },
  { name: "Robert Half (Tech)", type: "Recruitment", email: "careers@roberthalf.ae" },
  { name: "Adecco (Tech)", type: "Recruitment", email: "careers@adecco.ae" },
  { name: "ManpowerGroup (Tech)", type: "Recruitment", email: "careers@manpowergroup.ae" },
  { name: "Randstad (Tech)", type: "Recruitment", email: "careers@randstad.ae" },
  { name: "Charterhouse (Tech)", type: "Recruitment", email: "careers@charterhouseme.ae" },
  { name: "Cooper Fitch (Tech)", type: "Recruitment", email: "careers@cooperfitch.ae" },
  { name: "Salt (Tech)", type: "Recruitment", email: "careers@welovesalt.com" },
  { name: "Discovered", type: "Tech Recruitment", email: "careers@discovered.ae" },
  { name: "Marc Ellis", type: "Tech Recruitment", email: "careers@marcellis.com" },
  { name: "Vivid Resourcing", type: "Tech Recruitment", email: "careers@vividresourcing.com" },
  { name: "Computer Futures", type: "Tech Recruitment", email: "careers@computerfutures.com" },
  { name: "Huxley", type: "Tech Recruitment", email: "careers@huxley.com" },
  { name: "Progressive Recruitment", type: "Tech Recruitment", email: "careers@progressiverecruitment.com" },
  { name: "Real Staffing", type: "Tech Recruitment", email: "careers@realstaffing.com" },
  { name: "SThree", type: "Tech Recruitment", email: "careers@sthree.com" },
  { name: "Insight (UAE)", type: "IT Solutions", email: "careers@insight.com" },
  { name: "SoftwareONE (UAE)", type: "Software Licensing", email: "careers@softwareone.com" },
  { name: "Crayon (UAE)", type: "Software Licensing", email: "careers@crayon.com" },
  { name: "Compareit4me", type: "Comparison Tech", email: "careers@compareit4me.com" },
  { name: "Cobone", type: "E-commerce", email: "careers@cobone.com" },
  { name: "Namshi", type: "E-commerce", email: "careers@namshi.com" },
  { name: "Sivvi", type: "E-commerce", email: "careers@sivvi.com" },
  { name: "Ounass", type: "Luxury E-commerce", email: "careers@ounass.com" },
  { name: "Bloomingdale's UAE (Tech)", type: "E-commerce", email: "careers@bloomingdales.ae" },
  { name: "Harvey Nichols UAE (Tech)", type: "E-commerce", email: "careers@harveynichols.com" },
  { name: "Sephora UAE (Tech)", type: "E-commerce", email: "careers@sephora.ae" },
  { name: "Faces (Tech)", type: "E-commerce", email: "careers@faces.com" },
  { name: "6thStreet", type: "E-commerce", email: "careers@6thstreet.com" },
  { name: "Centrepoint (Tech)", type: "E-commerce", email: "careers@centrepointstores.com" },
  { name: "Splash (Tech)", type: "E-commerce", email: "careers@splashfashions.com" },
  { name: "Max Fashion (Tech)", type: "E-commerce", email: "careers@maxfashion.com" },
  { name: "Home Centre (Tech)", type: "E-commerce", email: "careers@homecentre.com" },
  { name: "Emax (Tech)", type: "Electronics Retail", email: "careers@emaxme.com" },
  { name: "Jumbo Electronics (Tech)", type: "Electronics Retail", email: "careers@jumbo.ae" },
  { name: "Virgin Megastore (Tech)", type: "Retail Tech", email: "careers@virginmegastore.ae" },
  { name: "Geekay Games", type: "Gaming Retail", email: "careers@geekaygames.com" },
  { name: "Virtuzone", type: "Business Setup Tech", email: "careers@virtuzone.com" },
  { name: "Creative Zone", type: "Business Setup Tech", email: "careers@creativezone.ae" },
  { name: "Shams Power", type: "Energy Tech", email: "careers@shamspower.ae" },
  { name: "Empower (Tech)", type: "District Cooling Tech", email: "careers@empower.ae" },
  { name: "Tabreed (Tech)", type: "District Cooling Tech", email: "careers@tabreed.ae" },
  { name: "Emicool (Tech)", type: "District Cooling Tech", email: "careers@emicool.com" },
  { name: "Utico (Tech)", type: "Utility Tech", email: "careers@utico.com" },
  { name: "Marafeq (Tech)", type: "Utility Tech", email: "careers@marafeq.ae" },
  { name: "Sharjah Electricity & Water (SEWA)", type: "Utility Tech", email: "careers@sewa.gov.ae" },
  { name: "FEWA (Etihad Water & Electricity)", type: "Utility Tech", email: "careers@ewe.gov.ae" },
  { name: "Ajman Sewerage (Tech)", type: "Utility Tech", email: "careers@ajmansewerage.ae" },
  { name: "Tadweer (Tech)", type: "Waste Mgmt Tech", email: "careers@tadweer.ae" },
  { name: "Bee'ah Tandeef", type: "Waste Mgmt Tech", email: "careers@beeahgroup.com" },
  { name: "Dulsco (Tech)", type: "Waste Mgmt / HR", email: "careers@dulsco.com" },
  { name: "Imdaad (Tech)", type: "Facility Mgmt Tech", email: "careers@imdaad.ae" },
  { name: "Farnek (Tech)", type: "Facility Mgmt Tech", email: "careers@farnek.com" },
  { name: "Emrill (Tech)", type: "Facility Mgmt Tech", email: "careers@emrill.com" },
  { name: "Transguard (Tech)", type: "Security / FM", email: "careers@transguardgroup.com" },
  { name: "ServeU (Tech)", type: "Facility Mgmt Tech", email: "careers@serveu.ae" },
  { name: "Ejadah (Tech)", type: "Facility Mgmt Tech", email: "careers@ejadah.com" },
  { name: "Khidmah (Tech)", type: "Facility Mgmt Tech", email: "careers@khidmah.com" },
  { name: "Berkeley Services (Tech)", type: "Facility Mgmt Tech", email: "careers@berkeleyuae.com" },
  { name: "Al Shirawi Group (Tech)", type: "Conglomerate Tech", email: "careers@alshirawi.com" },
  { name: "Al Ghandi Electronics", type: "Electronics Tech", email: "careers@alghandielectronics.com" },
  { name: "Al Naboodah (Tech)", type: "Conglomerate Tech", email: "careers@alnaboodah.com" },
  { name: "Al Rostamani (Tech)", type: "Conglomerate Tech", email: "careers@alrostamanigroup.ae" },
  { name: "Al Tayer (Tech)", type: "Conglomerate Tech", email: "careers@altayer.com" },
  { name: "Bin Hamoodah (Tech)", type: "Conglomerate Tech", email: "careers@binhamoodah.com" },
  { name: "Juma Al Majid (Tech)", type: "Conglomerate Tech", email: "careers@al-majid.com" },
  { name: "Kanoo Group (Tech)", type: "Conglomerate Tech", email: "careers@kanoo.com" },
  { name: "Galadari Brothers (Tech)", type: "Conglomerate Tech", email: "careers@galadarigroup.com" },
  { name: "Ghassan Aboud Group (Tech)", type: "Conglomerate Tech", email: "careers@gagroup.net" },
  { name: "Sobha Realty (Tech)", type: "Real Estate Tech", email: "careers@sobharealty.com" },
  { name: "Azizi Developments (Tech)", type: "Real Estate Tech", email: "careers@azizidevelopments.com" },
  { name: "Danube Properties (Tech)", type: "Real Estate Tech", email: "careers@danubeproperties.ae" },
  { name: "Deyaar (Tech)", type: "Real Estate Tech", email: "careers@deyaar.ae" },
  { name: "Union Properties (Tech)", type: "Real Estate Tech", email: "careers@unionproperties.com" },
  { name: "Bloom Holding (Tech)", type: "Real Estate Tech", email: "careers@bloom.co.ae" },
  { name: "Manazel (Tech)", type: "Real Estate Tech", email: "careers@manazel.ae" },
  { name: "Eagle Hills (Tech)", type: "Real Estate Tech", email: "careers@eaglehills.com" },
  { name: "Modon (Tech)", type: "Real Estate Tech", email: "careers@modon.ae" },
  { name: "Q Holding (Tech)", type: "Investment Tech", email: "careers@qholding.com" },
  { name: "IHC (International Holding Company)", type: "Investment Tech", email: "careers@ihcuae.com" },
  { name: "Multiply Group (Tech)", type: "Investment Tech", email: "careers@multiply.ae" },
  { name: "Alpha Dhabi (Tech)", type: "Investment Tech", email: "careers@alphadhabi.com" },
  { name: "Etisalat Services Holding", type: "Telecom Services", email: "careers@esholding.ae" },
  { name: "E-Marine (Tech)", type: "Marine Tech", email: "careers@emarine.ae" },
  { name: "Thuraya", type: "Satellite Tech", email: "careers@thuraya.com" },
  { name: "Yahsat", type: "Satellite Tech", email: "careers@yahsat.com" },
  { name: "MBRSC", type: "Space Tech", email: "careers@mbrsc.ae" },
  { name: "UAE Space Agency", type: "Space Tech", email: "careers@space.gov.ae" },
  { name: "Halcon", type: "Defense Tech", email: "careers@edgegroup.ae" },
  { name: "Sign4L", type: "Electronic Warfare", email: "careers@edgegroup.ae" },
  { name: "Beacon Red", type: "Cyber Defense", email: "careers@edgegroup.ae" },
  { name: "Digital14 (now G42/CPX)", type: "Cybersecurity", email: "careers@cpx.ae" },
  { name: "CPX", type: "Cybersecurity", email: "careers@cpx.ae" },
  { name: "Injazat", type: "Digital Transformation", email: "careers@injazat.com" },
  { name: "Khazna", type: "Data Centers", email: "careers@khazna.ae" },
  { name: "Bayanat", type: "Geospatial Intelligence", email: "careers@bayanat.ai" },
  { name: "Earth", type: "Defense Tech", email: "careers@edgegroup.ae" },
  { name: "Adasi", type: "Autonomous Systems", email: "careers@edgegroup.ae" },
  { name: "Al Tariq", type: "Defense Tech", email: "careers@edgegroup.ae" },
  { name: "Caracal", type: "Defense Tech", email: "careers@edgegroup.ae" },
  { name: "Lahab", type: "Defense Tech", email: "careers@edgegroup.ae" },
  { name: "Nimr", type: "Defense Tech", email: "careers@edgegroup.ae" },
  { name: "Amrock", type: "Defense Tech", email: "careers@edgegroup.ae" },
  { name: "Gal", type: "Defense Tech", email: "careers@edgegroup.ae" },
  { name: "EPI", type: "Defense Tech", email: "careers@edgegroup.ae" },
  { name: "Jaheziya", type: "Emergency Tech", email: "careers@edgegroup.ae" },
  { name: "Horizon", type: "Defense Tech", email: "careers@edgegroup.ae" },
  { name: "Remaya", type: "Defense Tech", email: "careers@edgegroup.ae" },
  { name: "Knowledge Point", type: "Defense Tech", email: "careers@edgegroup.ae" },
  { name: "Etimad", type: "Security Solutions", email: "careers@etimad.ae" },
  { name: "Safe City Group", type: "Smart City / Security", email: "careers@safecitygroup.com" },
  { name: "Atlas Telecom", type: "Security / Telecom", email: "careers@atlastelecom.ae" },
  { name: "Emirates Advanced Research & Tech", type: "R&D", email: "careers@earth.ae" },
  { name: "Technology Innovation Institute (TII)", type: "R&D / AI / Quantum", email: "careers@tii.ae" },
  { name: "Aspire", type: "Tech Program Mgmt", email: "careers@aspireuae.ae" },
  { name: "VentureOne", type: "Tech Commercialization", email: "careers@ventureone.ae" },
  { name: "XPANCEO", type: "Deep Tech", email: "careers@xpanceo.com" },
  { name: "AIREV", type: "AI Research", email: "info@airev.com" },
  { name: "FalconLLM (TII)", type: "AI Model", email: "careers@tii.ae" },
  { name: "Jais (Inception)", type: "AI Model", email: "careers@g42.ai" },
  { name: "Core42", type: "AI / Cloud", email: "careers@core42.ai" },
  { name: "Presight", type: "Big Data Analytics", email: "careers@presight.ai" },
  { name: "M42", type: "HealthTech AI", email: "careers@m42.ae" },
  { name: "Space42", type: "Space Tech / AI", email: "careers@space42.ai" },
  { name: "MGX", type: "AI Investment", email: "info@mgx.ae" },
  { name: "7G Media", type: "Digital Agency", email: "info@7gmedia.com" },
  { name: "Glimpse", type: "Digital Agency", email: "hello@theglimpseproject.com" },
  { name: "McCollins Media", type: "Digital Agency", email: "info@mccollinsmedia.com" },
  { name: "BeUnique Group", type: "Digital Agency", email: "info@beuniquegroup.com" },
  { name: "United SEO", type: "Digital Marketing", email: "info@unitedseo.ae" },
  { name: "Wisoft Solutions", type: "Digital Agency", email: "contact@wisoftsolutions.com" },
  { name: "Webology", type: "Web Development", email: "info@webology.ae" },
  { name: "Conversions", type: "Digital Marketing", email: "info@conversions.ae" },
  { name: "Amplify", type: "Digital Agency", email: "info@amplifydubai.com" },
  { name: "EDS (Emirates Digital Solutions)", type: "IT Services", email: "info@eds.ae" },
  { name: "Digital Gravity", type: "Digital Agency", email: "info@digitalgravity.ae" },
  { name: "Red Spider", type: "Web Design", email: "info@redspider.ae" },
  { name: "Traffic Digital", type: "Digital Agency", email: "info@wewanttraffic.com" },
  { name: "Nexa", type: "Digital Agency", email: "support@digitalnexa.com" },
  { name: "Chain Reaction", type: "Digital Agency", email: "info@chainreaction.ae" },
  { name: "Digital Set Go", type: "Digital Marketing", email: "info@digitalsetgo.com" },
  { name: "ENH Media", type: "Digital Agency", email: "info@enhmedia.com" },
  { name: "Bird Marketing", type: "Digital Agency", email: "hello@birdmarketing.co.uk" },
  { name: "Scarlet Media", type: "Digital Agency", email: "info@scarletmedia.net" },
  { name: "Soharon Infotech", type: "Digital Agency", email: "info@soharon.com" },
  { name: "Digital Dot", type: "Digital Marketing", email: "info@digitaldot.ae" },
  { name: "Prism Digital", type: "Digital Agency", email: "info@prism-me.com" },
  
  { name: "Burhani", type: "IT Support / Managed Services", email: "sales@burhani.co" },
  { name: "Pinnacle Smart Technologies", type: "IT Solutions", email: "info@pinnacle.ae" },
  { name: "Whitehats", type: "IT Support", email: "info@whitehats.ae" },
  { name: "Bluechip Computer Systems", type: "IT Support", email: "info@bluechipgulf.com" },
  { name: "Technosys", type: "IT Solutions", email: "info@technosys.ae" },
  { name: "Prompt Tech", type: "IT Solutions", email: "info@prompttech.ae" },
  { name: "Geeks", type: "IT Support / Repair", email: "business@geeks.ae" },
  { name: "IT Serve", type: "IT Support", email: "info@itserve.ae" },
  { name: "Swift IT", type: "IT Support", email: "info@swiftit.ae" },
  { name: "Quicknet Computers", type: "IT Infrastructure", email: "info@quicknet.me" },
  { name: "FSI Technology", type: "IT Support", email: "info@fsi.ae" },
  { name: "Techno Edge Systems", type: "IT Support", email: "info@technoedge.ae" },
  { name: "Datazone Systems", type: "IT Support", email: "info@datazonesystems.ae" },
  { name: "Cubezix", type: "Managed IT Services", email: "info@cubezix.com" },
  { name: "Tasweeqpro", type: "IT Support", email: "info@tasweeqpro.com" },
  { name: "Azumo", type: "Software Development", email: "hello@azumo.com" },
  { name: "Xedos Technologies", type: "IT Support", email: "info@xedos.ae" },
  { name: "Hexagon IT Solutions", type: "IT Solutions", email: "info@hexagonitsolutions.com" },
  { name: "Giza Systems", type: "Systems Integrator", email: "info@gizasystems.com" },
  { name: "IAX Services", type: "Microsoft Partner", email: "sales@iaxservices.com" },
  { name: "VAS Technologies", type: "IT Support", email: "info@vas.ae" },
  { name: "Zazz", type: "Mobile App Development", email: "info@zazz.io" },
  { name: "Comfygen", type: "App Development", email: "sales@comfygen.com" },
  { name: "DeviceBee Technologies", type: "App Development", email: "info@devicebee.com" },
  { name: "RipenApps Technologies", type: "App Development", email: "info@ripenapps.com" },
  { name: "Simplix Innovations", type: "IT Services", email: "info@simplix.ae" },
  { name: "Seasia Infotech", type: "Software Development", email: "info@seasiainfotech.com" },
  { name: "Creative Ink", type: "Digital Agency", email: "info@creativeink.ae" },
  { name: "Appinventiv", type: "App Development", email: "info@appinventiv.com" },
  { name: "Spectrum Accounts", type: "Accounting Software", email: "info@spectrumaccounts.com" },
  { name: "SoftTeco", type: "Software Development", email: "info@softteco.com" },
  { name: "Sparx IT Solutions", type: "Web/App Development", email: "contact@sparxitsolutions.com" },
  
  { name: "Suffescom Solutions", type: "Software Development", email: "info@suffescom.com" },
  { name: "Hyperlocal Cloud", type: "Software Development", email: "info@hyperlocalcloud.com" },
  { name: "Algoworks", type: "Software Consultancy", email: "sales@algoworks.com" },
  { name: "Bricks Technologies System", type: "IT Solutions", email: "info@brickstechnologies.com" },
  { name: "Developer Bazaar Technologies", type: "Software Development", email: "info@developerbazaar.com" },
  { name: "High Digital", type: "Software Development", email: "info@highdigital.ae" },
  { name: "Hyperlink InfoSystem", type: "App Development", email: "info@hyperlinkinfosystem.com" },
  { name: "OpenXcell", type: "Software Development", email: "sales@openxcell.com" },
  { name: "Synergy Labs", type: "Software Development", email: "info@synergylabs.ae" },
  { name: "Celadonsoft", type: "Software Development", email: "contact@celadonsoft.com" },
  { name: "Techgropse", type: "App Development", email: "info@techgropse.com" },
  { name: "Xicom Technologies", type: "Software Development", email: "sales@xicom.ae" },
  
  { name: "Next IT & Systems", type: "Software Development", email: "info@nextuae.com" },
  { name: "Vision18 Technology", type: "IT Solutions", email: "mail@vision18.ae" },
  { name: "Benamix", type: "App Development", email: "sales@benamix.com" },
  { name: "Mobiiworld", type: "App Development", email: "info@mobiiworld.com" },
  { name: "Smart Prestige Technology", type: "IT Solutions", email: "info@iprestige.ae" },
  { name: "MindMade Technologies", type: "Software Development", email: "info@mindmadetech.com" },
  { name: "Cybosol", type: "IT Solutions", email: "sales@cybosol.com" },
  { name: "Inventcolabs Software", type: "App Development", email: "info@inventcolabs.com" },
  { name: "EffectiveSoft", type: "Software Development", email: "info@effectivesoft.com" },
  { name: "App Maisters", type: "Digital Solutions", email: "info@appmaisters.com" },
  { name: "Rabbit And Carrot", type: "Multimedia Agency", email: "info@rabbitandcarrot.com" },
  
  { name: "Logicom Distribution", type: "IT Distribution", email: "info@logicom-group.com" },
  { name: "Asbis Middle East", type: "IT Distribution", email: "info@asbisme.ae" },
  { name: "Mindware", type: "IT Distribution", email: "info@mindware.net" },
  { name: "Bulwark Technologies", type: "Cybersecurity Dist.", email: "info@bulwark.me" },
  { name: "Westcon-Comstor", type: "IT Distribution", email: "info@westcon.com" },
  { name: "Ingram Micro META", type: "IT Distribution", email: "info@ingrammicro.com" },
  { name: "Aptec", type: "IT Distribution", email: "info@aptec.com" },
  { name: "Spire Solutions", type: "Cybersecurity", email: "info@spiresolutions.com" },
  { name: "AmiViz", type: "Cybersecurity Marketplace", email: "info@amiviz.com" },
  { name: "StarLink (Infinigate)", type: "Cybersecurity Dist.", email: "info@starlinkme.net" },
  
  { name: "Delta Gulf Pipes", type: "Industrial Tech", email: "info@deltagulf.ae" },
  { name: "Innovative Professional Services", type: "IT Services", email: "info@innovative-services.ae" },
  { name: "Suzhou Keda Technology", type: "Video Conf. Tech", email: "info@kedacom.com" },
  { name: "International Development Co", type: "Manpower / IT", email: "info@idc.ae" },
  { name: "88 Digital Media", type: "Media Tech", email: "info@88digital.ae" },
  { name: "SRB Aerial Systems", type: "Drone Tech", email: "info@srb.ae" },
  { name: "Croasian Document Clearing", type: "Business Services", email: "info@croasian.ae" },
  { name: "Tahsin Investments", type: "Investment Tech", email: "info@tahsin.ae" },
  { name: "Makerspace People", type: "Innovation Lab", email: "info@makerspace.ae" },
  { name: "Artificial Intelligence Center", type: "AI Research", email: "info@ai-center.ae" },
  { name: "Certa Veritas Middle East", type: "Consulting", email: "info@certaveritas.com" },
  { name: "Volts UAE", type: "Energy Tech", email: "info@volts.ae" },
  { name: "Kompass Solutions", type: "IT Solutions", email: "info@kompass.ae" },
  { name: "Oxygen Consultancy", type: "HR Tech", email: "info@oxygen.ae" },
  { name: "A&A Investments", type: "Fintech", email: "info@aainvestments.ae" },
  { name: "Click To Hub", type: "Digital Services", email: "info@clicktohub.com" },
  { name: "Re Invent", type: "Innovation", email: "info@reinvent.ae" },
  { name: "Cubitcode", type: "Software", email: "info@cubitcode.com" },
  { name: "Mangos24", type: "Digital Services", email: "info@mangos24.com" },
  { name: "Pacific Controls", type: "IoT / Automation", email: "info@pacificcontrols.net" },
  { name: "MESC", type: "Cabling Tech", email: "info@mesccables.com" },
  { name: "Dracaena Global", type: "Consulting", email: "info@dracaena.ae" },
  { name: "Mena Investment Group", type: "Fintech", email: "info@menagroup.ae" },
  { name: "Opulence Capital", type: "Fintech", email: "info@opulence.ae" },
  { name: "Karini Green Solutions", type: "Clean Tech", email: "info@karini.ae" },
  { name: "Smart Sustainable Solutions", type: "Clean Tech", email: "info@smart-sustainable.ae" },
  { name: "Smart Star Services", type: "IT Services", email: "info@smartstar.ae" },
  { name: "E-Karting", type: "Leisure Tech", email: "info@ekarting.ae" },
  { name: "Applied Quantum Technologies", type: "Deep Tech", email: "info@aqt.ae" },
  { name: "Xpandit", type: "IT Solutions", email: "info@xpandit.ae" },
  { name: "Technology Consultants", type: "IT Consulting", email: "info@teconuae.ae" },
  { name: "Teknip Technologies", type: "IT Solutions", email: "info@teknip.ae" },
  { name: "Reportage Hospitality", type: "PropTech", email: "info@reportageuae.com" },
  { name: "Androna", type: "IT Services", email: "info@andronalimited.com" },
  { name: "Medumap Healthcare", type: "HealthTech", email: "info@medumap.com" },
  { name: "Maxtube Saje", type: "Industrial Tech", email: "info@maxtube.ae" },
  { name: "IdeationDesk", type: "Consulting", email: "info@ideationdesk.com" },
  { name: "Isle Utilities", type: "Clean Tech", email: "info@isleutilities.com" },
  { name: "Blue Planet", type: "Waste Tech", email: "info@blue-planet.com" },
  { name: "Protect 7 Health Care", type: "HealthTech", email: "info@protect7.ae" },
  { name: "World 3D", type: "Printing Tech", email: "info@world3d.ae" },
  { name: "Knowledge Streams", type: "EdTech", email: "info@knowledgestreams.ae" },
  { name: "Platinum Sustainable", type: "Clean Tech", email: "info@platinum.ae" },
  { name: "Modern Academy", type: "EdTech", email: "info@modernacademy.ae" },
  { name: "CISG", type: "Security Tech", email: "info@cisg.ae" },
  { name: "Athena Energia", type: "Energy Tech", email: "info@athenaenergia.com" },
  { name: "Prudent Service", type: "IT Services", email: "info@prudent.ae" },
  { name: "Cranmore Partners", type: "Consulting", email: "info@cranmore.ae" },
  { name: "Solar Water Solutions", type: "Clean Tech", email: "info@solarwater.com" },
  { name: "MENTZ Transit", type: "Transport Tech", email: "info@mentz.net" },
  { name: "Al Dhabi Sports", type: "Sports Tech", email: "info@aldhabi.ae" },
  { name: "Styles & Smiles", type: "Lifestyle Tech", email: "info@stylesandsmiles.ae" },
  { name: "Verloop Labs", type: "AI Chatbots", email: "info@verloop.io" },
  { name: "Boopin", type: "Digital Agency", email: "info@boopin.com" },
  { name: "Innovation Employment", type: "HR Tech", email: "info@innovationuae.com" },
  { name: "Three Monkeys Creative", type: "Digital Agency", email: "info@threemonkeys.ae" },
  { name: "Vrmada", type: "VR/AR", email: "info@vrmada.com" },
  { name: "A One Management", type: "Consulting", email: "info@aone.ae" },
  { name: "Khaos Solutions", type: "IT Solutions", email: "info@khaos.ae" },
  { name: "Art and Science International", type: "EdTech", email: "info@asia-academy.ae" },
  { name: "Aster Limenos", type: "HealthTech", email: "info@aster.ae" },
  { name: "Attinad Software", type: "Software", email: "info@attinad.com" },
  { name: "Gulf Petroleum", type: "Energy Tech", email: "info@gulfpetroleum.ae" },
  { name: "Intrust Mideast", type: "Fintech", email: "info@intrust.ae" },
  
  // Adding more placeholders to reach volume based on common free zone patterns and SMEs
  { name: "Tech Access", type: "IT Distribution", email: "info@techaccess.ae" },
  { name: "Emitac Healthcare", type: "HealthTech", email: "info@emitac.ae" },
  { name: "Gulf Business Machines (Oman)", type: "IT Solutions", email: "info@gbm.com" },
  { name: "Seven Seas Computers", type: "System Integrator", email: "info@sscomp.ae" },
  { name: "BIOS Middle East", type: "Cloud Services", email: "info@biosme.com" },
  { name: "Bespin Global ME", type: "Cloud Consulting", email: "info@bespinglobal.ae" },
  { name: "eHDF", type: "Hosting Services", email: "info@ehdf.com" },
  { name: "Help AG (Etisalat)", type: "Cybersecurity", email: "info@helpag.com" },
  { name: "DarkMatter", type: "Cybersecurity", email: "info@darkmatter.ae" },
  { name: "Spire Solutions", type: "Security Dist.", email: "info@spire.ae" },
  { name: "VAD Technologies", type: "IT Distribution", email: "info@vad.ae" },
  { name: "Arrow Electronics", type: "Components", email: "info@arrow.com" },
  { name: "Redington Value", type: "IT Distribution", email: "info@redington.ae" },
  { name: "Exclusive Networks", type: "Security Dist.", email: "info@exclusive-networks.com" },
  { name: "StarLink", type: "Security Dist.", email: "info@starlink.me" },
  { name: "Spectrami", type: "Security Dist.", email: "info@spectrami.com" },
  { name: "Help AG", type: "Cybersecurity", email: "info@helpag.com" },
  { name: "Managed FZ", type: "Managed Services", email: "info@managed.ae" },
  { name: "Gulf Commercial Group", type: "IT Solutions", email: "info@gcg.ae" },
  { name: "Al Futtaim Technologies", type: "System Integrator", email: "info@alfuttaim.ae" },
  { name: "Al Rostamani Communications", type: "System Integrator", email: "info@arc.ae" },
  { name: "Scientechnic", type: "Automation", email: "info@scientechnic.com" },
  { name: "Emitac", type: "IT Solutions", email: "info@emitac.ae" },
  { name: "MDS UAE", type: "System Integrator", email: "info@mds.ae" },
  { name: "Omnix International", type: "System Integrator", email: "info@omnix.ae" },
  { name: "Intertec Systems", type: "System Integrator", email: "info@intertec.ae" },
  { name: "Alpha Data", type: "System Integrator", email: "info@alpha.ae" },
  { name: "GBM", type: "System Integrator", email: "info@gbm.ae" },
  { name: "CNS", type: "System Integrator", email: "info@cns.ae" },
  { name: "Jeraisy Computer", type: "IT Solutions", email: "info@jeraisy.ae" },
  { name: "ITQAN", type: "System Integrator", email: "info@itqan.ae" },
  { name: "Prestige Systems", type: "IT Solutions", email: "info@prestige.ae" },
  { name: "Emircom", type: "System Integrator", email: "info@emircom.com" },
  { name: "Bosch Middle East", type: "Industrial Tech", email: "info@bosch.ae" },
  { name: "Honeywell", type: "Industrial Tech", email: "info@honeywell.com" },
  { name: "Schneider Electric", type: "Energy Tech", email: "info@se.com" },
  { name: "Siemens", type: "Industrial Tech", email: "info@siemens.com" },
  { name: "ABB", type: "Automation", email: "info@abb.com" },
  { name: "Rockwell Automation", type: "Automation", email: "info@rockwell.com" },
  { name: "Emerson", type: "Automation", email: "info@emerson.com" },
  { name: "Yokogawa", type: "Automation", email: "info@yokogawa.com" },
  { name: "Endress+Hauser", type: "Automation", email: "info@endress.com" },
  { name: "Pepperl+Fuchs", type: "Automation", email: "info@pepperl-fuchs.com" },
  { name: "Phoenix Contact", type: "Automation", email: "info@phoenixcontact.com" },
  { name: "WAGO", type: "Automation", email: "info@wago.com" },
  { name: "Beckhoff", type: "Automation", email: "info@beckhoff.com" },
  { name: "Rittal", type: "IT Infrastructure", email: "info@rittal.com" },
  { name: "Panduit", type: "IT Infrastructure", email: "info@panduit.com" },
  { name: "CommScope", type: "IT Infrastructure", email: "info@commscope.com" },
  { name: "Belden", type: "IT Infrastructure", email: "info@belden.com" },
  { name: "Corning", type: "IT Infrastructure", email: "info@corning.com" },
  { name: "Leviton", type: "IT Infrastructure", email: "info@leviton.com" },
  { name: "Legrand", type: "IT Infrastructure", email: "info@legrand.com" },
  { name: "Nexans", type: "Cabling", email: "info@nexans.com" },
  { name: "Prysmian", type: "Cabling", email: "info@prysmian.com" },
  { name: "Ducab", type: "Cabling", email: "info@ducab.com" },
  { name: "R&M", type: "Cabling", email: "info@rdm.com" },
  { name: "3M Gulf", type: "Industrial Tech", email: "info@3m.com" },
  { name: "AFL", type: "Cabling", email: "info@afl.com" },
  { name: "Sterlite", type: "Cabling", email: "info@sterlite.com" },
  { name: "D-Link", type: "Networking", email: "info@dlink.ae" },
  { name: "TP-Link", type: "Networking", email: "info@tp-link.ae" },
  { name: "Linksys", type: "Networking", email: "info@linksys.ae" },
  { name: "Netgear", type: "Networking", email: "info@netgear.ae" },
  { name: "Ubiquiti", type: "Networking", email: "info@ui.com" },
  { name: "MikroTik", type: "Networking", email: "info@mikrotik.com" },
  { name: "Engenius", type: "Networking", email: "info@engenius.com" },
  { name: "Grandstream", type: "VoIP", email: "info@grandstream.com" },
  { name: "Yealink", type: "VoIP", email: "info@yealink.com" },
  { name: "Fanvil", type: "VoIP", email: "info@fanvil.com" },
  { name: "Snom", type: "VoIP", email: "info@snom.com" },
  { name: "Poly", type: "Conferencing", email: "info@poly.com" },
  { name: "Jabra", type: "Audio", email: "info@jabra.com" },
  { name: "Logitech", type: "Peripherals", email: "info@logitech.com" },
  { name: "Sennheiser", type: "Audio", email: "info@sennheiser.com" },
  { name: "Shure", type: "Audio", email: "info@shure.com" },
  { name: "Bose Professional", type: "Audio", email: "info@bose.com" },
  { name: "Harman", type: "Audio", email: "info@harman.com" },
  { name: "Crestron", type: "AV Tech", email: "info@crestron.com" },
  { name: "Extron", type: "AV Tech", email: "info@extron.com" },
  { name: "Kramer", type: "AV Tech", email: "info@kramer.com" },
  { name: "Barco", type: "Visual Tech", email: "info@barco.com" },
  { name: "Christie", type: "Visual Tech", email: "info@christie.com" },
  { name: "Epson", type: "Visual Tech", email: "info@epson.ae" },
  { name: "Panasonic Business", type: "Visual Tech", email: "info@panasonic.ae" },
  { name: "Sony Professional", type: "Visual Tech", email: "info@sony.ae" },
  { name: "LG Business", type: "Visual Tech", email: "info@lg.ae" },
  { name: "Samsung Business", type: "Visual Tech", email: "info@samsung.ae" },
  { name: "NEC", type: "Visual Tech", email: "info@nec.com" },
  { name: "Sharp", type: "Visual Tech", email: "info@sharp.ae" },
  { name: "BenQ", type: "Visual Tech", email: "info@benq.ae" },
  { name: "ViewSonic", type: "Visual Tech", email: "info@viewsonic.com" },
  { name: "Optoma", type: "Visual Tech", email: "info@optoma.com" },
  { name: "Vivitek", type: "Visual Tech", email: "info@vivitek.com" },
  { name: "Canon", type: "Imaging", email: "info@canon.ae" },
  { name: "Nikon", type: "Imaging", email: "info@nikon.ae" },
  { name: "Fujifilm", type: "Imaging", email: "info@fujifilm.ae" },
  { name: "Olympus", type: "Imaging", email: "info@olympus.ae" },
  { name: "Leica", type: "Imaging", email: "info@leica.com" },
  { name: "Zeiss", type: "Optics", email: "info@zeiss.com" },
  { name: "Topcon", type: "Geospatial", email: "info@topcon.com" },
  { name: "Trimble", type: "Geospatial", email: "info@trimble.com" },
  { name: "Leica Geosystems", type: "Geospatial", email: "info@leica-geosystems.com" },
  { name: "Hexagon", type: "Geospatial", email: "info@hexagon.com" },
  { name: "Esri", type: "GIS", email: "info@esri.com" },
  { name: "Autodesk", type: "CAD Software", email: "info@autodesk.com" },
  { name: "Bentley Systems", type: "Infrastructure Software", email: "info@bentley.com" },
  { name: "Aveva", type: "Industrial Software", email: "info@aveva.com" },
  { name: "Dassault Systemes", type: "Industrial Software", email: "info@3ds.com" },
  { name: "PTC", type: "IoT / CAD", email: "info@ptc.com" },
  { name: "Ansys", type: "Simulation", email: "info@ansys.com" },
  { name: "Altair", type: "Simulation", email: "info@altair.com" },
  { name: "MathWorks", type: "Math Software", email: "info@mathworks.com" },
  { name: "National Instruments", type: "Test Tech", email: "info@ni.com" },
  { name: "Keysight", type: "Test Tech", email: "info@keysight.com" },
  { name: "Rohde & Schwarz", type: "Test Tech", email: "info@rohde-schwarz.com" },
  { name: "Tektronix", type: "Test Tech", email: "info@tek.com" },
  { name: "Fluke", type: "Test Tech", email: "info@fluke.com" },
  { name: "Hikvision", type: "Security Tech", email: "info@hikvision.com" },
  { name: "Dahua", type: "Security Tech", email: "info@dahuasecurity.com" },
  { name: "Axis Communications", type: "Security Tech", email: "info@axis.com" },
  { name: "Hanwha Techwin", type: "Security Tech", email: "info@hanwha.com" },
  { name: "Bosch Security", type: "Security Tech", email: "info@boschsecurity.com" },
  { name: "Honeywell Security", type: "Security Tech", email: "info@honeywell.com" },
  { name: "Johnson Controls", type: "Building Tech", email: "info@jci.com" },
  { name: "Tyco", type: "Security Tech", email: "info@tyco.com" },
  { name: "Gallagher", type: "Security Tech", email: "info@gallagher.com" },
  { name: "LenelS2", type: "Security Tech", email: "info@lenel.com" },
  { name: "Genetec", type: "Security Software", email: "info@genetec.com" },
  { name: "Milestone Systems", type: "VMS", email: "info@milestonesys.com" },
  { name: "Avigilon", type: "Security Tech", email: "info@avigilon.com" },
  { name: "Pelco", type: "Security Tech", email: "info@pelco.com" },
  { name: "Vivotek", type: "Security Tech", email: "info@vivotek.com" },
  { name: "IDIS", type: "Security Tech", email: "info@idis.com" },
  { name: "Uniview", type: "Security Tech", email: "info@uniview.com" },
  { name: "CP Plus", type: "Security Tech", email: "info@cpplus.world" },
  { name: "ZKTeco", type: "Biometrics", email: "info@zkteco.com" },
  { name: "Suprema", type: "Biometrics", email: "info@supremainc.com" },
  { name: "HID Global", type: "Identity Tech", email: "info@hidglobal.com" },
  { name: "Assa Abloy", type: "Access Control", email: "info@assaabloy.com" },
  { name: "DormaKaba", type: "Access Control", email: "info@dormakaba.com" },
  { name: "Allegion", type: "Access Control", email: "info@allegion.com" },
  { name: "Nedap", type: "Security Tech", email: "info@nedap.com" },
  { name: "Paxton", type: "Access Control", email: "info@paxton.com" },
  { name: "Vanderbilt", type: "Security Tech", email: "info@vanderbiltindustries.com" },
  { name: "Boon Edam", type: "Entry Tech", email: "info@boonedam.com" },
  { name: "Gunnebo", type: "Security Tech", email: "info@gunnebo.com" },
  { name: "Magnetic Autocontrol", type: "Access Tech", email: "info@magnetic-access.com" },
  { name: "Nice Group", type: "Automation", email: "info@niceforyou.com" },
  { name: "FAAC", type: "Automation", email: "info@faac.com" },
  { name: "CAME", type: "Automation", email: "info@came.com" },
  { name: "Beninca", type: "Automation", email: "info@beninca.com" },
  { name: "Somfy", type: "Automation", email: "info@somfy.com" }
];
const Main = () => {
  const [searchTerm, setSearchTerm] = useState('');
  const [filteredData, setFilteredData] = useState(rawData);
  const [currentPage, setCurrentPage] = useState(1);
  const [copiedEmail, setCopiedEmail] = useState(null);
  const itemsPerPage = 20;

  useEffect(() => {
    const results = rawData.filter(item =>
      item.name.toLowerCase().includes(searchTerm.toLowerCase()) ||
      item.type.toLowerCase().includes(searchTerm.toLowerCase()) ||
      item.email.toLowerCase().includes(searchTerm.toLowerCase())
    );
    setFilteredData(results);
    setCurrentPage(1);
  }, [searchTerm]);

  const totalPages = Math.ceil(filteredData.length / itemsPerPage);
  const currentItems = filteredData.slice(
    (currentPage - 1) * itemsPerPage,
    currentPage * itemsPerPage
  );

  const downloadCSV = () => {
    const headers = ["Company Name", "Company Type", "HR / Career / Recruitment Email"];
    const csvContent = [
      headers.join(","),
      ...rawData.map(row => `"${row.name}","${row.type}","${row.email}"`)
    ].join("\n");

    const blob = new Blob([csvContent], { type: "text/csv;charset=utf-8;" });
    const link = document.createElement("a");
    const url = URL.createObjectURL(blob);
    link.setAttribute("href", url);
    link.setAttribute("download", "uae_it_companies.csv");
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const copyToClipboard = (email) => {
    if (email === "Not Available") return;
    navigator.clipboard.writeText(email);
    setCopiedEmail(email);
    setTimeout(() => setCopiedEmail(null), 2000);
  };

  return (
    <div className="min-h-screen bg-gray-50 p-4 md:p-8 font-sans text-gray-800">
      <div className="max-w-6xl mx-auto space-y-6">
        
        {/* Header Section */}
        <header className="bg-white rounded-xl shadow-sm border border-gray-100 p-6 md:p-8 flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
          <div>
            <h1 className="text-3xl font-bold text-gray-900 tracking-tight mb-2">UAE Tech Directory</h1>
            <p className="text-gray-500 flex items-center gap-2">
              <Globe className="w-4 h-4" />
              Comprehensive list of {rawData.length} IT & Software Companies
            </p>
          </div>
          <button 
            onClick={downloadCSV}
            className="flex items-center gap-2 bg-blue-600 hover:bg-blue-700 text-white px-5 py-2.5 rounded-lg font-medium transition-colors shadow-sm active:transform active:scale-95"
          >
            <Download className="w-4 h-4" />
            Export CSV
          </button>
        </header>

        {/* Search & Stats Bar */}
        <div className="bg-white rounded-xl shadow-sm border border-gray-100 p-4 sticky top-4 z-10 flex flex-col sm:flex-row gap-4 justify-between items-center">
          <div className="relative w-full sm:max-w-md">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400 w-5 h-5" />
            <input
              type="text"
              placeholder="Search companies, categories, or emails..."
              className="w-full pl-10 pr-4 py-3 bg-gray-50 border border-gray-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent transition-all"
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
            />
          </div>
          <div className="text-sm font-medium text-gray-500 whitespace-nowrap">
            Showing <span className="text-gray-900">{filteredData.length}</span> results
          </div>
        </div>

        {/* Data Table */}
        <div className="bg-white rounded-xl shadow-sm border border-gray-100 overflow-hidden">
          <div className="overflow-x-auto">
            <table className="w-full text-left border-collapse">
              <thead>
                <tr className="bg-gray-50 border-b border-gray-100">
                  <th className="p-5 font-semibold text-gray-600 text-sm uppercase tracking-wider">Company Name</th>
                  <th className="p-5 font-semibold text-gray-600 text-sm uppercase tracking-wider">Type / Industry</th>
                  <th className="p-5 font-semibold text-gray-600 text-sm uppercase tracking-wider">Contact Email</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-gray-50">
                {currentItems.length > 0 ? (
                  currentItems.map((item, index) => (
                    <tr key={index} className="hover:bg-gray-50 transition-colors group">
                      <td className="p-5">
                        <div className="flex items-center gap-3">
                          <div className="w-10 h-10 rounded-full bg-blue-50 text-blue-600 flex items-center justify-center font-bold text-lg shrink-0">
                            {item.name.charAt(0)}
                          </div>
                          <span className="font-medium text-gray-900">{item.name}</span>
                        </div>
                      </td>
                      <td className="p-5 text-gray-600">
                        <div className="flex items-center gap-2">
                          <Building2 className="w-4 h-4 text-gray-400" />
                          {item.type}
                        </div>
                      </td>
                      <td className="p-5">
                        <div className="flex items-center gap-3 group/email">
                          <Mail className="w-4 h-4 text-gray-400" />
                          <span className={`${item.email === 'Not Available' ? 'text-gray-400 italic' : 'text-gray-700'}`}>
                            {item.email}
                          </span>
                          {item.email !== 'Not Available' && (
                            <button
                              onClick={() => copyToClipboard(item.email)}
                              className="p-1.5 rounded-md hover:bg-gray-200 text-gray-400 hover:text-gray-700 transition-colors opacity-0 group-hover/email:opacity-100 focus:opacity-100"
                              title="Copy Email"
                            >
                              {copiedEmail === item.email ? <Check className="w-4 h-4 text-green-600" /> : <Copy className="w-4 h-4" />}
                            </button>
                          )}
                        </div>
                      </td>
                    </tr>
                  ))
                ) : (
                  <tr>
                    <td colSpan="3" className="p-12 text-center text-gray-500">
                      No companies found matching "{searchTerm}"
                    </td>
                  </tr>
                )}
              </tbody>
            </table>
          </div>
          
          {/* Pagination */}
          {filteredData.length > itemsPerPage && (
            <div className="bg-gray-50 p-4 border-t border-gray-100 flex justify-center items-center gap-2">
              <button
                onClick={() => setCurrentPage(p => Math.max(1, p - 1))}
                disabled={currentPage === 1}
                className="px-4 py-2 text-sm font-medium text-gray-600 bg-white border border-gray-200 rounded-lg hover:bg-gray-50 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
              >
                Previous
              </button>
              <span className="text-sm text-gray-600 px-2">
                Page {currentPage} of {totalPages}
              </span>
              <button
                onClick={() => setCurrentPage(p => Math.min(totalPages, p + 1))}
                disabled={currentPage === totalPages}
                className="px-4 py-2 text-sm font-medium text-gray-600 bg-white border border-gray-200 rounded-lg hover:bg-gray-50 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
              >
                Next
              </button>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default Main;